name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Change user
        run: su rafay_test
        
      - name: Check working directory
        run: pwd
        working-directory: /var/www/edusoft_school_management

      - name: Check user
        run: whoami
        working-directory: /var/www/edusoft_school_management

      - name: Pull lateset code
        run: su rafay_test && git pull origin main
        working-directory: /var/www/edusoft_school_management

      - name: Install dependencies
        run: npm install
        working-directory: /var/www/edusoft_school_management

      - name: Restart PM2 process
        run: sudo pm2 restart Edusoft
        working-directory: /var/www/edusoft_school_management
